from __future__ import annotations

from django import forms
from django.db import models
from django.http import HttpRequest, HttpResponse

from typing import *

from . import HasContext

A = Type[tuple[Any]]
K = Type[dict[Any, Any]]

class HasHttpMethods(Protocol):
    def delete(self, request: HttpRequest, *args: A, **kwargs: K) -> HttpResponse: ...
    def get(self, request: HttpRequest, *args: A, **kwargs: K) -> HttpResponse: ...
    def head(self, request: HttpRequest, *args: A, **kwargs: K) -> HttpResponse: ...
    def options(self, request: HttpRequest, *args: A, **kwargs: K) -> HttpResponse: ...
    def patch(self, request: HttpRequest, *args: A, **kwargs: K) -> HttpResponse: ...
    def post(self, request: HttpRequest, *args: A, **kwargs: K) -> HttpResponse: ...
    def put(self, request: HttpRequest, *args: A, **kwargs: K) -> HttpResponse: ...
    def trace(self, request: HttpRequest, *args: A, **kwargs: K) -> HttpResponse: ...

class UserFormMixin:
    user: Type[models.Model]
    def __init__(self, *args: A, **kwargs: K) -> None: ...

class FormWithUserMixin:
    def get_form_kwargs(self) -> dict[Any, Any]: ...
    def get_form_class(self) -> Type[forms.Form]: ...

class CSRFExemptMixin:
    def dispatch(
        self,
        request: HttpRequest,
        *args: A,
        **kwargs: K,
    ) -> HttpResponse: ...

CsrfExemptMixin = CSRFExemptMixin

class MultipleFormsMixin(HasContext, HasHttpMethods):
    context: dict[str, Any]
    form_classes: dict[str, forms.Form]
    initial: dict[str, dict[str, Any]]
    get_form: type[forms.Form]
    def __init__(self, *args: A, **kwargs: K) -> None: ...
    def get_form_classes(self) -> list[forms.Form]: ...
    def get_forms(self) -> dict[str, forms.Form]: ...
    def get_form_kwargs(self, name: str) -> dict[str, Any]: ...
    def validate_forms(self) -> bool: ...
    def forms_valid(self) -> HttpResponse: ...
    def forms_invalid(self) -> HttpResponse: ...

class MultipleModelFormsMixin(MultipleFormsMixin):
    instances: dict[str, models.Model]
    def get_instances(self) -> dict[str, models.Model]: ...
    def get_form_kwargs(self, name: str) -> dict[str, Any]: ...
