from __future__ import annotations
from typing import *

from django.db.models import Model, QuerySet

from . import A, K

class SelectRelatedMixin:
    select_related: Union[str, Iterable[str]]
    def get_select_related(self) -> list[str]: ...
    def get_queryset(self) -> QuerySet[Model]: ...

class PrefetchRelatedMixin:
    prefetch_related: Union[str, Iterable[str]]
    def get_prefetch_related(self) -> list[str]: ...
    def get_queryset(self) -> QuerySet[Model]: ...

class OrderableListMixin:
    orderable_fields: list[str]
    orderable_field_default: str
    orderable_direction_default: str
    def __init__(self, *args: A, **kwargs: K) -> None: ...
    def get_orderable_fields(self) -> list[str]: ...
    def get_orderable_field_default(self) -> str: ...
    def get_orderable_direction_default(self) -> str: ...
    def get_order_from_request(self) -> Iterable[str]: ...
    def get_queryset(self) -> QuerySet[Model]: ...
